##
# Terraform Docs
# Configuration: https://terraform-docs.io/user-guide/configuration/
#
formatter: "markdown" # this is required

version: ">= 0.17.0"

#header-from: main.tf
#footer-from: footer.tf

recursive:
  enabled: false
  path: modules

sections:
  hide:
    - modules
  show: []

content: |-
  ## Example

  ```hcl
  {{ include "examples/main.tf" }}
  ```
  
  {{ .Requirements }}

  {{ .Inputs }}
  
  {{ .Outputs }}
  
  {{ .Resources }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: false
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
